### ISSUE TITLE
encrypted message fee lost

### ISSUE THREAD

**Issue by lumenano** [TheCircleFoundation/conceal-gui#1]
When an encrypted message is sent from the "Send message" screen, it never gets confirmed. It shows up on the transactions list as unconfirmed. When the "transaction details" screen (double-click on transaction) is opened, the fee is displayed as 0.00 CCX (even though it had a non-zero value on the "Send message" screen), which may explain why it is unconfirmed.

I suppose that unconfirmed transactions are eventually discarded from the pool.

**Comment by lumenano** [comment]
To clarify, there is no problem with "crypto comments" on the "Send" screen.

**Comment by krypt0x** [comment]
Thanks. Your description is very detailed.

**Comment by krypt0x** [comment]
It seems related to self destructive messages only. Permanent messages are working normally.

**Comment by lumenano** [comment]
The two unconfirmed transactions are still in the unconfirmed pool -- at least they are still showing up in both the cli and gui wallets. I expected there to be a time limit after which they would be discarded. Maybe this is a separate issue.

**Comment by krypt0x** [comment]
bug fixed. thanks
