### ISSUE TITLE
request for Reply-To message attached to payment

### ISSUE THREAD

**Issue by lumenano** [TheCircleFoundation/conceal-gui#2]
Right now in the GUI wallet it is possible to attach an encrypted message to a payment on the "Send" screen, but no option to include a Reply-To message (nor an option for self-destruct), like there is on the "Send message" screen.

It would be best to merge the "Send message" screen  with the "Send" screen, so that on one screen there would be payment, encrypted message, reply-to, and message self-destruct. But if not, there should at least be Reply-To for payments, so that a payment recipient can know the origin of the payment.

**Comment by krypt0x** [comment]
bug fixed. thanks
